Repository IBM/ibm-cert-manager-operator, pull requests merged in 2020-08, with the labels that each got.

#83 Update operator version to 3.7.0 and CICD changes
  .osdk-scorecard.yaml
  Makefile
  common/scripts/config_docker.sh
  common/scripts/get_image_sha_digest.sh
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/certificate-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/clusterissuer-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/ibm-cert-manager-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/issuer-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
  deploy/operator.yaml
  pkg/resources/constants.go
  version/version.go
Labels: approved, lgtm, size/XXL

#84 Expose resources in CR
  deploy/crds/operator.ibm.com_certmanagers_crd.yaml
  pkg/apis/operator/v1alpha1/certmanager_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/certmanager/deploys.go
Labels: approved, lgtm, size/L

#85 Remove product version metering annotation
  deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/ibm-cert-manager-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/constants.go
Labels: approved, lgtm, size/S

#86 Update UBI image to 8.2-345
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#87 Update operand references to SHAs
  deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/ibm-cert-manager-operator.v3.7.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#88 RHACM - multiclusterhub APIGroup and version update
  deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/ibm-cert-manager-operator.v3.7.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/certmanager/prereqs.go
Labels: approved, lgtm, size/XS

#89 update go version to 1.14 and update operand shas
  common/scripts/get_image_sha_digest.sh
  deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/ibm-cert-manager-operator.v3.7.0.clusterserviceversion.yaml
  go.mod
Labels: approved, lgtm, size/M

#90 update operand SHAs
  Makefile
  deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/ibm-cert-manager-operator.v3.7.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S
