Repository IBM/ibm-cert-manager-operator, pull requests merged in 2020-04, with the labels that each got.

#44 Update README.md
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#45 Resolve cv-lint issues
  deploy/access-role.yaml
  deploy/access-rolebinding.yaml
  deploy/crds/certificate-crd.yaml
  deploy/crds/certificate_cr.yaml
  deploy/crds/clusterissuer-crd.yaml
  deploy/crds/clusterissuer_cr.yaml
  deploy/crds/issuer-crd.yaml
  deploy/crds/issuer_cr.yaml
  deploy/crds/operator.ibm.com_certmanagers_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: approved, lgtm, size/M

#46 Generate CSV for 3.6.0 release
  Makefile
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/certificate-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/clusterissuer-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/issuer-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#47 Fix certManagerStatus initialization in certmanager CR
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#48 Update readme with security context requirements
  README.md
Labels: approved, lgtm, size/XS

#49 Updating certManagerStatus initial value in alm-examples
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#50 Adding RHACM support
  deploy/role.yaml
  pkg/controller/certmanager/certmanager_controller.go
  pkg/controller/certmanager/prereqs.go
Labels: approved, lgtm, size/M

#51 Operator Updates
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/constants.go
Labels: approved, lgtm, size/S

#52 Update copyright statement
  Makefile
Labels: approved, lgtm, size/XS
