Repository IBM/ibm-cert-manager-operator, pull requests merged in 2020-05, with the labels that each got.

#53 Add RHACM required role in 3.6.0 CSV
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#54 Update image to latest UBI
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#55 Update image reference for operands
  Makefile
  common/scripts/get_image_sha_digest.sh
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/certmanager/deploys.go
  pkg/resources/constants.go
  pkg/resources/util.go
Labels: approved, lgtm, size/L

#56 Increase operator resource limits
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#57 CSV and README updates
  README.md
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#58 Set host parameters to false in operator deployment
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#59 Update operand image references to digest
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#60 Beta channel changes
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
Labels: approved, lgtm, size/XS

#63 3.6.1 CSV version updates
  .osdk-scorecard.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.1/certificate-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.1/clusterissuer-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.1/ibm-cert-manager-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.1/issuer-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.1/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#65 DisableHostNetwork default value changed to true
  pkg/apis/operator/v1alpha1/certmanager_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/certmanager/deploys.go
Labels: approved, lgtm, size/S

#67 Update README.md
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#66 Update ibm-cert-manager-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.1/ibm-cert-manager-operator.v3.6.1.clusterserviceversion.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#69 fix disable host network changes
  pkg/controller/certmanager/deploys.go
Labels: approved, lgtm, size/XS

#70 Add spec.version
  deploy/crds/operator.ibm.com_certmanagers_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.1/operator.ibm.com_certmanagers_crd.yaml
  pkg/apis/operator/v1alpha1/certmanager_types.go
Labels: approved, lgtm, size/XS

#71 3.6.1 move to beta channel and Operator SHA Update
  deploy/olm-catalog/ibm-cert-manager-operator/3.6.1/ibm-cert-manager-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
Labels: approved, lgtm, size/XS
