Repository IBM/ibm-cert-manager-operator, pull requests merged in 2020-03, with the labels that each got.

#28 Update CSV to include shared CA CR files
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#29 Update CSV to mostly pass red hat certification
  deploy/access-role.yaml
  deploy/access-rolebinding.yaml
  deploy/clusterrole.yaml
  deploy/crds/operator.ibm.com_certmanagers_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/csv-config.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/operator.ibm.com_certmanagers_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  docs/adoption-guide.md
  docs/cert-manager-operator-spec.md
  pkg/apis/operator/v1alpha1/certmanager_types.go
  pkg/controller/certmanager/certmanager_controller.go
  pkg/resources/constants.go
Labels: approved, lgtm, size/XL

#30 Fix logic handling image registry
  pkg/controller/certmanager/deploys.go
  pkg/resources/constants.go
Labels: approved, lgtm, size/M

#31 Update the ubi base image to be based on the sha instead of the version.
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#32 Use the correct configmap watcher version.
  pkg/resources/constants.go
Labels: approved, lgtm, size/XS

#33 Add metering annotations
  pkg/resources/constants.go
  pkg/resources/deployments.go
Labels: approved, lgtm, size/S

#34 Update CSV to pass red hat certification
  deploy/crds/certificate-crd.yaml
  deploy/crds/certificate_cr.yaml
  deploy/crds/clusterissuer-crd.yaml
  deploy/crds/clusterissuer_cr.yaml
  deploy/crds/issuer-crd.yaml
  deploy/crds/issuer_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/certificate-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/clusterissuer-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/issuer-crd.yaml
  pkg/resources/deployments.go
Labels: approved, lgtm, size/XXL

#35 Add metering annotations to our operator
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#36 Added the controllers argument
  pkg/resources/constants.go
Labels: approved, lgtm, size/XS

#37 Prevent removing additional deployment labels
  pkg/controller/certmanager/deploys.go
Labels: approved, lgtm, size/S

#38 Added additional field to determine if it's ocp 3.11
  Makefile
  common/config/.golangci.yml
  deploy/crds/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/operator.ibm.com_certmanagers_crd.yaml
  pkg/apis/operator/v1alpha1/certmanager_types.go
  pkg/controller/certmanager/deploys.go
Labels: approved, lgtm, size/S

#39 Update version to 3.5.0
  version/version.go
Labels: approved, lgtm, size/XS

#40 Add the exact repo to pull from in the default example CR.
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#41 Updated readme and removed docs folder
  README.md
  docs/adoption-guide.md
  docs/cert-manager-operator-spec.md
  docs/design-spec.md
Labels: approved, lgtm, size/XL

#42 Update operator image version and channel
  OWNERS
  common/scripts/push_csv.sh
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#43 Renaming field ocp311 to disableHostNetwork
  deploy/crds/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/operator.ibm.com_certmanagers_crd.yaml
  pkg/apis/operator/v1alpha1/certmanager_types.go
  pkg/controller/certmanager/deploys.go
Labels: approved, lgtm, size/M
