Repository IBM/ibm-cert-manager-operator, pull requests merged in 2021-11, with the labels that each got.

#206 bump eus version to 3.8.3
  .osdk-scorecard.yaml
  OWNERS
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.8.3/certificate-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.8.3/clusterissuer-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.8.3/ibm-cert-manager-operator.v3.8.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.8.3/issuer-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.8.3/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, lgtm

#207 update go mod to 1.17 for EUS
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#208 updated version to 3.16.0
  .osdk-scorecard.yaml
  common/scripts/bump_up_csv.sh
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/acme.cert-manager.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/acme.cert-manager.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/cert-manager.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/cert-manager.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/cert-manager.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/cert-manager.io_issuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/certmanager.k8s.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/certmanager.k8s.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/certmanager.k8s.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/certmanager.k8s.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/certmanager.k8s.io_issuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/certmanager.k8s.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/ibm-cert-manager-operator.v3.16.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
  version/version.go
Labels: size/XXL, lgtm, approved

#209 changed containerImage tag to fix linter error
  OWNERS
  common/scripts/bump_up_csv.sh
  deploy/olm-catalog/ibm-cert-manager-operator/3.8.3/ibm-cert-manager-operator.v3.8.3.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#210 refresh v1alpha1 leaf certs
  pkg/controller/certificaterefresh/certificaterefresh_controller.go
Labels: lgtm, approved, size/L

#211 updated liveness and readiness probes' configurations (#134)
  pkg/resources/constants.go
  pkg/resources/containers.go
Labels: lgtm, approved, size/S

#212 changed dns sanitization when converting certs to parse URLs instead …
  pkg/controller/certificate/converter.go
Labels: lgtm, approved, size/S

#213 fixed pod restart incorrectly restarting pods
  pkg/controller/podrefresh/podrefresh_controller.go
Labels: lgtm, approved, size/L
