Repository IBM/ibm-cert-manager-operator, pull requests merged in 2021-02, with the labels that each got.

#104 Enable leaf certificate refresh
  Makefile
  deploy/crds/operator.ibm.com_certmanagers_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/ibm-cert-manager-operator.v3.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/operator.ibm.com_certmanagers_crd.yaml
  deploy/role.yaml
  go.sum
  pkg/apis/operator/v1alpha1/certmanager_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_certificaterefresh.go
  pkg/controller/certificaterefresh/certificaterefresh_controller.go
  pkg/resources/constants.go
  pkg/resources/util.go
Labels: approved, lgtm, size/XXL

#105 Update duration of root CA to 2 years
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/ibm-cert-manager-operator.v3.9.0.clusterserviceversion.yaml
  pkg/controller/certificaterefresh/certificaterefresh_controller.go
  pkg/resources/constants.go
Labels: approved, lgtm, size/L

#106 remove clusterissuer
  deploy/crds/clusterissuer-crd.yaml
  deploy/crds/clusterissuer_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/ibm-cert-manager-operator.v3.9.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XXL

#107 Delete clusterissuer-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/clusterissuer-crd.yaml
Labels: approved, lgtm, size/XXL

#108 update manifest-tool version to v1.0.3
  Makefile
Labels: approved, lgtm, size/M

#109 Update ibm-cert-manager-operator.v3.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/ibm-cert-manager-operator.v3.9.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#110 Add duration/renewbefore in certificate CR
  deploy/crds/certificate_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
Labels: approved, lgtm, size/XS

#111 move cs ca issuer logic + adopt operand digest auto-update
  deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/ibm-cert-manager-operator.v3.9.0.clusterserviceversion.yaml
  pkg/controller/certmanager/certmanager_controller.go
Labels: approved, lgtm, size/M
