Repository IBM/ibm-cert-manager-operator, pull requests merged in 2021-12, with the labels that each got.

#215 bump version to 3.17.0
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/acme.cert-manager.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/acme.cert-manager.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/cert-manager.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/cert-manager.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/cert-manager.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/cert-manager.io_issuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/certmanager.k8s.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/certmanager.k8s.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/certmanager.k8s.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/certmanager.k8s.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/certmanager.k8s.io_issuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/certmanager.k8s.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/ibm-cert-manager-operator.v3.17.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.17.0/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
  version/version.go
Labels: size/XXL, lgtm, approved

#217 remove codecov
  Makefile
  common/scripts/codecov.sh
Labels: lgtm, approved, size/L

#216 ignore status updates to v1alpha1 resources when converting
  pkg/controller/certificate/certificate_controller.go
  pkg/controller/issuer/issuer_controller.go
Labels: lgtm, approved, size/M
