Repository IBM/ibm-cert-manager-operator, pull requests merged in 2021-08, with the labels that each got.

#137 added v1.4.2 jetstack APIs
  Makefile
  deploy/crds/acme.cert-manager.io_orders_crd.yaml
  deploy/crds/acme.cert-manager.io_v1_order_cr.yaml
  deploy/crds/cert-manager.io_certificaterequests_crd.yaml
  deploy/crds/cert-manager.io_certificates_crd.yaml
  deploy/crds/cert-manager.io_clusterissuers_crd.yaml
  deploy/crds/cert-manager.io_issuers_crd.yaml
  deploy/crds/cert-manager.io_v1_certificate_cr.yaml
  deploy/crds/cert-manager.io_v1_certificaterequest_cr.yaml
  deploy/crds/cert-manager.io_v1_issuer_cr.yaml
  deploy/crds/certmanager.k8s.io_challenges_crd.yaml
  deploy/crds/certmanager.k8s.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.12.0/certmanager.k8s.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.12.0/certmanager.k8s.io_orders_crd.yaml
  pkg/apis/acme/group.go
  pkg/apis/acme/v1/doc.go
  pkg/apis/acme/v1/order_types.go
  pkg/apis/acme/v1/register.go
  pkg/apis/acme/v1/types_issuer.go
  pkg/apis/acme/v1/zz_generated.deepcopy.go
  pkg/apis/addtoscheme_acme_v1.go
  pkg/apis/addtoscheme_certmanager_v1.go
  pkg/apis/certmanager/v1/certificate_types.go
  pkg/apis/certmanager/v1/certificaterequest_types.go
  pkg/apis/certmanager/v1/const.go
  pkg/apis/certmanager/v1/doc.go
  pkg/apis/certmanager/v1/generic_issuer.go
  pkg/apis/certmanager/v1/issuer_types.go
  pkg/apis/certmanager/v1/register.go
  pkg/apis/certmanager/v1/types.go
  pkg/apis/certmanager/v1/zz_generated.deepcopy.go
  pkg/apis/meta/group.go
  pkg/apis/meta/v1/doc.go
  pkg/apis/meta/v1/register.go
  pkg/apis/meta/v1/types.go
  pkg/apis/meta/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#138 changed containerImage tag to latest to be consistent with containers
  deploy/olm-catalog/ibm-cert-manager-operator/3.12.0/ibm-cert-manager-operator.v3.12.0.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#139 V1 certificates
  deploy/crds/cert-manager.io_certificates_crd.yaml
  pkg/apis/certmanager/v1/certificate_types.go
  pkg/apis/certmanager/v1/zz_generated.deepcopy.go
Labels: size/XXL, lgtm, approved

#142 opt-in of ubi base image automated builds
  Makefile
  base_images.json
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: lgtm, approved, size/S

#144 add related images in csv
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
Labels: lgtm, approved, size/S

#146 added nil annotation check to conversion logic
  pkg/controller/certificate/certificate_controller.go
  pkg/controller/issuer/issuer_controller.go
Labels: lgtm, size/XS, approved

#148 updated code to deploy cainjector successfully
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/certificate/certificate_controller.go
  pkg/controller/certmanager/prereqs.go
  pkg/controller/issuer/issuer_controller.go
  pkg/resources/pods.go
  pkg/resources/rbac.go
Labels: lgtm, approved, size/L

#147 fixed v1alpha1 Certificate conversion to handle empty Duration and Re…
  pkg/controller/certificate/certificate_controller.go
Labels: lgtm, size/XS, approved

#145 add liveness and readiness probes
  cmd/manager/main.go
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#149 Update cert manager controller to v1.5
  SECURITY_CONTACTS
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/acme.cert-manager.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/acme.cert-manager.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/cert-manager.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/cert-manager.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/operator.ibm.com_certmanagers_crd.yaml
  deploy/role.yaml
  pkg/controller/certmanager/deploys.go
  pkg/controller/certmanager/prereqs.go
  pkg/resources/constants.go
  pkg/resources/containers.go
  pkg/resources/pods.go
  pkg/resources/rbac.go
  pkg/resources/util.go
Labels: size/XXL, lgtm, approved

#153 changed containerImage tag to fix bundle linting
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#154 fixed run-csv configmap error
  .gitignore
  Makefile
  cmd/manager/main.go
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
  pkg/controller/certificate/certificate_controller.go
Labels: lgtm, approved, size/M

#152 feat: Set v1alpha1 objects as the owner of v1 objects
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/certificate/certificate_controller.go
  pkg/controller/issuer/issuer_controller.go
Labels: lgtm, approved, size/M

#163 add pod refresh controller
  cmd/manager/main.go
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
  pkg/controller/add_podrefresh.go
  pkg/controller/certificaterefresh/certificaterefresh_controller.go
  pkg/controller/podrefresh/podrefresh_controller.go
Labels: lgtm, approved, size/L

#166 changed operator to deploy cert-manager v1.5.1
  .gitignore
  Makefile
  SECURITY_CONTACTS
  cmd/manager/main.go
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/acme.cert-manager.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/acme.cert-manager.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/cert-manager.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/cert-manager.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/operator.ibm.com_certmanagers_crd.yaml
  deploy/role.yaml
  pkg/apis/acme/v1/types_issuer.go
  pkg/apis/acme/v1/zz_generated.deepcopy.go
  pkg/controller/add_podrefresh.go
  pkg/controller/certificate/certificate_controller.go
  pkg/controller/certificate/converter.go
  pkg/controller/certificaterefresh/certificaterefresh_controller.go
  pkg/controller/certmanager/deploys.go
  pkg/controller/certmanager/prereqs-webhook.go
  pkg/controller/certmanager/prereqs.go
  pkg/controller/issuer/converter.go
  pkg/controller/issuer/issuer_controller.go
  pkg/controller/podrefresh/podrefresh_controller.go
  pkg/resources/constants.go
  pkg/resources/containers.go
  pkg/resources/pods.go
  pkg/resources/rbac.go
  pkg/resources/util.go
  pkg/resources/webhook_resources.go
Labels: size/XXL, lgtm, approved

#165 opt-in of ubi base image automated builds (#142)
  Makefile
  base_images.json
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: lgtm, size/S

#167 reduced size of CRDs to work with OLM bundle
  Makefile
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/acme.cert-manager.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/acme.cert-manager.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/cert-manager.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/cert-manager.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/cert-manager.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/cert-manager.io_issuers_crd.yaml
Labels: size/XXL, lgtm, approved

#169 fixed podrefresh restarting pods too many times
  pkg/controller/podrefresh/podrefresh_controller.go
Labels: lgtm, approved, size/M

#170 update go version to 1.17
  go.mod
Labels: lgtm, size/XS, approved

#171 updated mutation and validation webhook apiversion to v1
  cmd/manager/main.go
  go.mod
  pkg/controller/certmanager/certmanager_controller.go
Labels: lgtm, approved, size/M
