Repository IBM/ibm-cert-manager-operator, pull requests merged in 2021-10, with the labels that each got.

#189 updated conversion logic to update IAM webhook annotation
  common/config/.golangci.yml
  pkg/controller/certificate/certificate_controller.go
Labels: lgtm, approved, size/M

#190 create configmap watcher configmap
  pkg/resources/rbac.go
Labels: lgtm, size/XS, approved

#191 fixed wrong name when getting IAM webhook
  pkg/controller/certificate/certificate_controller.go
Labels: lgtm, approved, size/S

#192 fixed certificate controller not adding labels properly to v1 Certifi…
  pkg/controller/certificate/certificate_controller.go
  pkg/controller/certificaterefresh/certificaterefresh_controller.go
Labels: lgtm, approved, size/M

#195 fixed nil error in conversion code during leaf refresh
  pkg/controller/certificate/certificate_controller.go
Labels: lgtm, size/XS, approved
