Repository IBM/ibm-cert-manager-operator, pull requests merged in 2021-09, with the labels that each got.

#168 update logs
  pkg/controller/podrefresh/podrefresh_controller.go
Labels: lgtm, size/XS, approved

#172 revert operand image version to 0.15.0
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
Labels: lgtm, approved, size/S

#173 update go mod to 1.17
  go.mod
Labels: lgtm, approved, size/M

#175 added empty slice check for rhacm check
  pkg/controller/certmanager/prereqs.go
Labels: lgtm, size/XS, approved

#174 bump version to 4.0.0 for future branch
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/acme.cert-manager.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/acme.cert-manager.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/cert-manager.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/cert-manager.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/cert-manager.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/cert-manager.io_issuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_issuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/ibm-cert-manager-operator.v4.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
  version/version.go
Labels: size/XXL, lgtm, approved

#176 removed hard-coded namespace from rbac
  deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
  pkg/controller/certmanager/prereqs.go
  pkg/resources/rbac.go
Labels: lgtm, approved, size/M

#177 updated version to 3.14.0
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.14.0/cert-manager.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.14.0/cert-manager.io_issuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.14.0/certmanager.k8s.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.14.0/certmanager.k8s.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.14.0/certmanager.k8s.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.14.0/certmanager.k8s.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.14.0/certmanager.k8s.io_issuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.14.0/certmanager.k8s.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.14.0/ibm-cert-manager-operator.v3.14.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.14.0/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
  version/version.go
Labels: size/XXL, lgtm, approved

#179 remove 4.0.0 version from master and update configma-watcher operand
  deploy/olm-catalog/ibm-cert-manager-operator/3.14.0/ibm-cert-manager-operator.v3.14.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/acme.cert-manager.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/acme.cert-manager.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/cert-manager.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/cert-manager.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/cert-manager.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/cert-manager.io_issuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_issuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/ibm-cert-manager-operator.v4.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/operator.ibm.com_certmanagers_crd.yaml
Labels: size/XXL, lgtm, approved

#180 fixed RBAC creation issue
  pkg/controller/certmanager/prereqs.go
Labels: lgtm, size/XS, approved

#181 added docker label for git commit
  Makefile
  build/Dockerfile
Labels: lgtm, approved, size/S

#182 changed conversion logic to only convert if existing v1alpha1 Certifi…
  pkg/controller/certificate/certificate_controller.go
  pkg/resources/constants.go
Labels: lgtm, approved, size/L

#183 fixed fresh install never converting v1alpha1 Certificates because co…
  pkg/controller/certificate/certificate_controller.go
Labels: size/XS, approved

#184 innocuous change to trigger Travis build
  OWNERS
Labels: size/XS, approved

#186 convert leaf certificates when CA is updated
  pkg/controller/certificate/certificate_controller.go
  pkg/controller/certificaterefresh/certificaterefresh_controller.go
Labels: lgtm, approved, size/L

#185 disable certificate and issuer reconciliation to support RHACM 2.2
  pkg/controller/certificate/certificate_controller.go
  pkg/controller/certmanager/certmanager_controller.go
  pkg/controller/certmanager/prereqs.go
  pkg/controller/issuer/issuer_controller.go
Labels: lgtm, approved, size/M
