Repository IBM/ibm-cert-manager-operator, pull requests merged in 2021-04, with the labels that each got.

#117 Remove cs-ca-certificate, cs-ca-issuer, cs-ss-issuer
  deploy/crds/certificate_cr.yaml
  deploy/crds/issuer-crd.yaml
  deploy/crds/issuer_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.10.0/ibm-cert-manager-operator.v3.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.10.0/issuer-crd.yaml
  pkg/controller/certmanager/certmanager_controller.go
  pkg/resources/certmanager_resources.go
Labels: approved, lgtm, size/XXL

#118 eus operator ubi updates
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/olm-catalog/ibm-cert-manager-operator/3.8.2/ibm-cert-manager-operator.v3.8.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#119 ubi updates
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/olm-catalog/ibm-cert-manager-operator/3.10.0/ibm-cert-manager-operator.v3.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#120 Fix indentation in certmanager CRD
  deploy/crds/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.10.0/operator.ibm.com_certmanagers_crd.yaml
Labels: approved, lgtm, size/XL

#121 added new quality of life commands to test changes quickly
  Makefile
  OWNERS
  common/scripts/replace-dev-images.sh
  deploy/olm-catalog/ibm-cert-manager-operator/3.10.0/ibm-cert-manager-operator.v3.10.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XL
