Repository IBM/ibm-cert-manager-operator, pull requests merged in 2022-11, with the labels that each got.

#288 leaf refresh enhancement
  controllers/cert-manager/certificaterefresh_controller.go
Labels: lgtm, approved, size/L

#291 hide RHACM error message
  controllers/certmanager/certificate_controller.go
  controllers/certmanager/issuer_controller.go
  controllers/operator/certmanager_controller.go
Labels: lgtm, size/XS, approved

#293 bump version for 3.19.7
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#295 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#296 update prow change into ltsr
  common/Makefile.common.mk
Labels: lgtm, size/XS, approved

#298 bumped version to 4.0.0
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/S
