Repository IBM/ibm-cert-manager-operator, pull requests merged in 2022-05, with the labels that each got.

#253 added back replaces field to CSV
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#254 Revert "fixed v1 certificate not updating when v1alpha1 updated (#252)"
  controllers/certmanager/certificate_controller.go
Labels: lgtm, approved, size/S

#255 add Yuchen Li to the owner file in cert-manager
  OWNERS
Labels: lgtm, size/XS, approved, ok-to-test, do-not-merge/invalid-owners-file

#257 updated version to 3.21.0
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#258 cert-manager OOM issue update
  controllers/operator/certmanager_controller.go
  main.go
Labels: lgtm, size/XS, approved
