Repository IBM/ibm-cert-manager-operator, pull requests merged in 2022-10, with the labels that each got.

#282 updated v1 CRDs to 1.9.1 from community
  .gitignore
  controllers/operator/certmanager_controller.go
  controllers/operator/v1CRDs.go
  controllers/resources/crd_variables.go
  controllers/resources/v1crds/certificaterequests.yaml
  controllers/resources/v1crds/certificates.yaml
  controllers/resources/v1crds/challenges.yaml
  controllers/resources/v1crds/clusterissuers.yaml
  controllers/resources/v1crds/issuers.yaml
  controllers/resources/v1crds/orders.yaml
Labels: size/XXL, lgtm, approved

#283 bump ltsr verison to 3.21.5
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#284 Ltsr crd update to 1.9.1
  .gitignore
  Makefile
  apis/cert-manager/v1/certificate_types.go
  apis/cert-manager/v1/issuer_types.go
  apis/cert-manager/v1/types.go
  apis/cert-manager/v1/zz_generated.deepcopy.go
  apis/meta.cert-manager/v1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/cert-manager.io_certificates.yaml
  bundle/manifests/cert-manager.io_issuers.yaml
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/cert-manager.io_certificates.yaml
  config/crd/bases/cert-manager.io_issuers.yaml
Labels: lgtm, approved, size/L

#285 moved back the v1 APIs to apis/
  apis/acme.cert-manager/v1/groupversion_info.go
  apis/acme.cert-manager/v1/types_issuer.go
  apis/acme.cert-manager/v1/zz_generated.deepcopy.go
  apis/cert-manager/v1/certificate_types.go
  apis/cert-manager/v1/doc.go
  apis/cert-manager/v1/groupversion_info.go
  apis/cert-manager/v1/issuer_types.go
  apis/cert-manager/v1/types.go
  apis/cert-manager/v1/zz_generated.deepcopy.go
  apis/meta.cert-manager/v1/doc.go
  apis/meta.cert-manager/v1/groupversion_info.go
  apis/meta.cert-manager/v1/types.go
  apis/meta.cert-manager/v1/zz_generated.deepcopy.go
  controllers/cert-manager/certificaterefresh_controller.go
  controllers/cert-manager/podrefresh_controller.go
  controllers/cert-manager/suite_test.go
  controllers/cert-manager/v1_add_label_controller.go
  controllers/cert-manager/v1alpha1_add_label_controller.go
  controllers/certmanager/certificate_controller.go
  controllers/certmanager/certificate_converter.go
  controllers/certmanager/issuer_controller.go
  controllers/certmanager/issuer_converter.go
  main.go
Labels: lgtm, approved, size/M

#287 cherry-pick: moved back the v1 APIs to apis/ (#285)
  apis/acme.cert-manager/v1/groupversion_info.go
  apis/acme.cert-manager/v1/types_issuer.go
  apis/acme.cert-manager/v1/zz_generated.deepcopy.go
  apis/cert-manager/v1/certificate_types.go
  apis/cert-manager/v1/doc.go
  apis/cert-manager/v1/groupversion_info.go
  apis/cert-manager/v1/issuer_types.go
  apis/cert-manager/v1/types.go
  apis/cert-manager/v1/zz_generated.deepcopy.go
  apis/meta.cert-manager/v1/doc.go
  apis/meta.cert-manager/v1/groupversion_info.go
  apis/meta.cert-manager/v1/types.go
  apis/meta.cert-manager/v1/zz_generated.deepcopy.go
  controllers/cert-manager/certificaterefresh_controller.go
  controllers/cert-manager/podrefresh_controller.go
  controllers/cert-manager/suite_test.go
  controllers/cert-manager/v1_add_label_controller.go
  controllers/cert-manager/v1alpha1_add_label_controller.go
  controllers/certmanager/certificate_controller.go
  controllers/certmanager/certificate_converter.go
  controllers/certmanager/issuer_controller.go
  controllers/certmanager/issuer_converter.go
  main.go
Labels: lgtm, approved, size/M

#289 no-op PR to trigger PROW build for new images
  README.md
Labels: lgtm, size/XS, approved
