Repository IBM/ibm-cert-manager-operator, pull requests merged in 2022-03, with the labels that each got.

#232 fixed missing v1alpha1 ClusterIssuer CRD
  apis/certmanager/v1alpha1/issuer_types.go
  bundle/manifests/certmanager.k8s.io_clusterissuers.yaml
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/crd/bases/certmanager.k8s.io_clusterissuers.yaml
  config/crd/kustomization.yaml
Labels: size/XXL, lgtm, approved

#236 reduce size of CRDs
  Makefile
  bundle/manifests/acme.cert-manager.io_challenges.yaml
  bundle/manifests/acme.cert-manager.io_orders.yaml
  bundle/manifests/cert-manager.io_certificaterequests.yaml
  bundle/manifests/cert-manager.io_certificates.yaml
  bundle/manifests/cert-manager.io_clusterissuers.yaml
  bundle/manifests/cert-manager.io_issuers.yaml
  bundle/manifests/certmanager.k8s.io_certificaterequests.yaml
  bundle/manifests/certmanager.k8s.io_certificates.yaml
  bundle/manifests/certmanager.k8s.io_challenges.yaml
  bundle/manifests/certmanager.k8s.io_clusterissuers.yaml
  bundle/manifests/certmanager.k8s.io_issuers.yaml
  bundle/manifests/certmanager.k8s.io_orders.yaml
Labels: size/XXL, lgtm, approved

#233 updated version to 3.19.0
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/S

#238 Fix replaces
  Makefile
  bundle/manifests/acme.cert-manager.io_challenges.yaml
  bundle/manifests/acme.cert-manager.io_orders.yaml
  bundle/manifests/cert-manager.io_certificaterequests.yaml
  bundle/manifests/cert-manager.io_certificates.yaml
  bundle/manifests/cert-manager.io_clusterissuers.yaml
  bundle/manifests/cert-manager.io_issuers.yaml
  bundle/manifests/certmanager.k8s.io_certificaterequests.yaml
  bundle/manifests/certmanager.k8s.io_certificates.yaml
  bundle/manifests/certmanager.k8s.io_challenges.yaml
  bundle/manifests/certmanager.k8s.io_clusterissuers.yaml
  bundle/manifests/certmanager.k8s.io_issuers.yaml
  bundle/manifests/certmanager.k8s.io_orders.yaml
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: size/XXL, lgtm, approved

#239 updated operand versions for v3.19.0
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#240 added scripts to reduce CRD size in bundle
  .gitignore
  Makefile
  apis/meta.cert-manager/v1/zz_generated.deepcopy.go
  common/Makefile.common.mk
  controllers/resources/constants.go
  go.sum
  hack/fixup-cert-manager-manifests.py
  hack/reduce-bundle-crds.sh
Labels: lgtm, approved, size/L

#241 set leader election namespace for cainjector
  controllers/operator/deploys.go
Labels: lgtm, size/XS, approved

#242 fix missing patch permission for controller pod
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/operator/certmanager_controller.go
  controllers/resources/rbac.go
Labels: lgtm, size/XS, approved

#243 updated CRDs to 1.7.1
  Makefile
  apis/acme.cert-manager/v1/types_issuer.go
  apis/acme.cert-manager/v1/zz_generated.deepcopy.go
  apis/cert-manager/v1/certificate_types.go
  apis/cert-manager/v1/issuer_types.go
  apis/cert-manager/v1/types.go
  apis/cert-manager/v1/zz_generated.deepcopy.go
  bundle/manifests/acme.cert-manager.io_challenges.yaml
  bundle/manifests/acme.cert-manager.io_orders.yaml
  bundle/manifests/cert-manager.io_certificaterequests.yaml
  bundle/manifests/cert-manager.io_certificates.yaml
  bundle/manifests/cert-manager.io_clusterissuers.yaml
  bundle/manifests/cert-manager.io_issuers.yaml
  config/crd/bases/acme.cert-manager.io_challenges.yaml
  config/crd/bases/acme.cert-manager.io_orders.yaml
  config/crd/bases/cert-manager.io_certificaterequests.yaml
  config/crd/bases/cert-manager.io_certificates.yaml
  config/crd/bases/cert-manager.io_clusterissuers.yaml
  config/crd/bases/cert-manager.io_issuers.yaml
Labels: size/XXL, lgtm, approved

#244 add update role for services resources
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/operator/certmanager_controller.go
Labels: lgtm, size/XS, approved
