Repository IBM/ibm-cert-manager-operator, pull requests merged in 2022-09, with the labels that each got.

#276 cleanup configmap watcher references
  controllers/operator/deploys.go
  controllers/resources/constants.go
  controllers/resources/containers.go
  controllers/resources/deployments.go
  controllers/resources/pods.go
Labels: lgtm, approved, size/L

#277 remove cm watcher labels
  controllers/operator/deploys.go
  controllers/resources/constants.go
  controllers/resources/containers.go
  controllers/resources/deployments.go
  controllers/resources/pods.go
Labels: lgtm, approved, size/L

#279 bump version to 3.21.4
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#280 version bump and doc change
  CONTRIBUTING.md
  Makefile
  README.md
  apis/operator/v1alpha1/certmanager_types.go
  bundle.Dockerfile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_certmanagers.yaml
  bundle/metadata/annotations.yaml
  common/config/mdl.rb
  config/crd/bases/operator.ibm.com_certmanagers.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: size/XXL, lgtm, approved
