Repository IBM/ibm-cert-manager-operator, pull requests merged in 2022-02, with the labels that each got.

#223 bump version to 3.18.0
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/acme.cert-manager.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/acme.cert-manager.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/cert-manager.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/cert-manager.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/cert-manager.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/cert-manager.io_issuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/certmanager.k8s.io_certificaterequests_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/certmanager.k8s.io_certificates_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/certmanager.k8s.io_challenges_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/certmanager.k8s.io_clusterissuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/certmanager.k8s.io_issuers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/certmanager.k8s.io_orders_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/ibm-cert-manager-operator.v3.18.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
  version/version.go
Labels: size/XXL, lgtm, approved

#224 bump operand versions to 1.4.0-jetstack.1.5.1
  deploy/olm-catalog/ibm-cert-manager-operator/3.18.0/ibm-cert-manager-operator.v3.18.0.clusterserviceversion.yaml
Labels: lgtm, approved, size/S

#225 bump eus version for cert-manager v3.8.4
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.8.4/certificate-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.8.4/clusterissuer-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.8.4/ibm-cert-manager-operator.v3.8.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.8.4/issuer-crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/3.8.4/operator.ibm.com_certmanagers_crd.yaml
  deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, lgtm, approved

#227 added missing subjectaccessreviews.authorization.k8s.io rbac
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/operator/certmanager_controller.go
Labels: lgtm, approved, size/S

#228 apply secret cache filter by TYPE
  controllers/resources/constants.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved, size/M

#229 added back RHACM permissions
  config/rbac/role.yaml
  controllers/operator/certmanager_controller.go
  controllers/operator/prereqs.go
Labels: lgtm, approved, size/S

#230 changed v1alpha1 CRDs back to non subresource status
  apis/certmanager/v1alpha1/certificate_types.go
  apis/certmanager/v1alpha1/certificaterequest_types.go
  apis/certmanager/v1alpha1/challenge_types.go
  apis/certmanager/v1alpha1/issuer_types.go
  apis/certmanager/v1alpha1/order_types.go
  bundle/manifests/certmanager.k8s.io_certificaterequests.yaml
  bundle/manifests/certmanager.k8s.io_certificates.yaml
  bundle/manifests/certmanager.k8s.io_challenges.yaml
  bundle/manifests/certmanager.k8s.io_issuers.yaml
  bundle/manifests/certmanager.k8s.io_orders.yaml
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/crd/bases/certmanager.k8s.io_certificaterequests.yaml
  config/crd/bases/certmanager.k8s.io_certificates.yaml
  config/crd/bases/certmanager.k8s.io_challenges.yaml
  config/crd/bases/certmanager.k8s.io_issuers.yaml
  config/crd/bases/certmanager.k8s.io_orders.yaml
Labels: lgtm, approved, size/M
