Repository IBM/ibm-cert-manager-operator, pull requests merged in 2022-07, with the labels that each got.

#267 compatibility clause to CertManager CRDs
  bundle/manifests/operator.ibm.com_certmanagers.yaml
  config/crd/bases/operator.ibm.com_certmanagers.yaml
Labels: lgtm, size/XS, approved

#269 add dependency
  controllers/cert-manager/certificaterefresh_controller.go
  controllers/cert-manager/v1_add_label_controller.go
  controllers/certmanager/issuer_controller.go
Labels: lgtm, approved, size/S

#270 added list options to podrefresh logic
  controllers/cert-manager/podrefresh_controller.go
Labels: lgtm, approved, size/M

#271 bump version for 3.19.3
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M
