Repository IBM/ibm-cert-manager-operator, pull requests merged in 2023-10, with the labels that each got.

#372 fixed label controller not finding cert secrets because of cache filt…
  controllers/cert-manager/v1_add_label_controller.go
  controllers/cert-manager/v1alpha1_add_label_controller.go
  main.go
Labels: lgtm, approved, size/M

#374 Bump cert manager to 3.25.9 for release 3.23.9
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#373 updated controller-runtime
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_certmanagerconfigs.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/cert-manager.io_issuers.yaml
  config/crd/bases/operator.ibm.com_certmanagerconfigs.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/samples/operator_v1_certmanagerconfig.yaml
  controllers/operator/certmanager_controller.go
  controllers/operator/prereqs-webhook.go
  controllers/operator/suite_test.go
  go.mod
  go.sum
  main.go
Labels: size/XXL, lgtm, approved

#377 Ephemeral storage limit
  controllers/operator/deploys.go
Labels: lgtm, size/XS, approved

#375 Community code sync for operand, update CRDs
  apis/acme.cert-manager/v1/types_issuer.go
  apis/acme.cert-manager/v1/zz_generated.deepcopy.go
  apis/cert-manager/v1/certificate_types.go
  apis/cert-manager/v1/issuer_types.go
  apis/cert-manager/v1/types.go
  apis/cert-manager/v1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/acme.cert-manager.io_challenges.yaml
  bundle/manifests/acme.cert-manager.io_orders.yaml
  bundle/manifests/cert-manager.io_certificaterequests.yaml
  bundle/manifests/cert-manager.io_certificates.yaml
  bundle/manifests/cert-manager.io_clusterissuers.yaml
  bundle/manifests/cert-manager.io_issuers.yaml
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/acme.cert-manager.io_challenges.yaml
  config/crd/bases/acme.cert-manager.io_orders.yaml
  config/crd/bases/cert-manager.io_certificaterequests.yaml
  config/crd/bases/cert-manager.io_certificates.yaml
  config/crd/bases/cert-manager.io_clusterissuers.yaml
  config/crd/bases/cert-manager.io_issuers.yaml
  config/manager/manager.yaml
  go.mod
  go.sum
Labels: size/XXL, lgtm, approved

#378 update go mod, net pkg
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#379 updated default sizing to match medium size
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/resources/certmanager.go
Labels: lgtm, approved, size/S
