Repository IBM/ibm-cert-manager-operator, pull requests merged in 2023-06, with the labels that each got.

#342 Update cert manager description
  README.md
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#343 Update cert manager description
  README.md
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#341 bump version for 3.19.13
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#344 [CM LTSR] "disconnected" annotation for certification assessment
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#345 [LTSR] Update ImagePullPolicy to IfNotPresent
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, size/XS, approved

#340 [LTSR] Make podrestart label more accurate
  controllers/cert-manager/podrefresh_controller.go
Labels: lgtm, approved, size/S

#346 [Cert Manager] bump version to 4.1.0
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/samples/operator_v1_certmanagerconfig.yaml
  controllers/resources/certmanager.go
Labels: lgtm, approved, size/S

#338 [Bedrock 4.1 CM] "disconnected" annotation for certification assessment
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#339 [Bedrock 4.1 CM] Update ImagePullPolicy to IfNotPresent
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, size/XS, approved
