Repository IBM/ibm-cert-manager-operator, pull requests merged in 2023-09, with the labels that each got.

#364 add ephemeral storage request to container
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/operator/deploys.go
  controllers/resources/certmanager.go
  controllers/resources/constants.go
  controllers/resources/containers.go
Labels: lgtm, approved, size/S

#367 bump version for 3.19.16
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#368 update crds and cert manager image versions after uplift
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  controllers/resources/v1crds/certificaterequests.yaml
  controllers/resources/v1crds/certificates.yaml
  controllers/resources/v1crds/challenges.yaml
  controllers/resources/v1crds/clusterissuers.yaml
  controllers/resources/v1crds/issuers.yaml
  controllers/resources/v1crds/orders.yaml
Labels: lgtm, approved, size/L

#371 fixed labels in v1 CRDs to remove Helm templating
  controllers/resources/v1crds/certificaterequests.yaml
  controllers/resources/v1crds/certificates.yaml
  controllers/resources/v1crds/challenges.yaml
  controllers/resources/v1crds/clusterissuers.yaml
  controllers/resources/v1crds/issuers.yaml
  controllers/resources/v1crds/orders.yaml
Labels: lgtm, approved, size/M

#369 Post install delegation checker
  Makefile
  PROJECT
  bundle.Dockerfile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_certmanagers.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/certmanager.k8s.io_challenges.yaml
  config/crd/bases/certmanager.k8s.io_clusterissuers.yaml
  config/crd/bases/certmanager.k8s.io_issuers.yaml
  config/crd/bases/certmanager.k8s.io_orders.yaml
  config/crd/bases/operator.ibm.com_certmanagers.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/cert-manager/certificaterefresh_controller.go
  controllers/cert-manager/podrefresh_controller.go
  controllers/cert-manager/suite_test.go
  controllers/cert-manager/v1_add_label_controller.go
  controllers/cert-manager/v1alpha1_add_label_controller.go
  controllers/certmanager/certificate_controller.go
  controllers/certmanager/issuer_controller.go
  controllers/certmanager/suite_test.go
  controllers/operator/certmanager_controller.go
  controllers/operator/postdelegationchecker_controller.go
  controllers/operator/suite_test.go
  go.mod
  go.sum
  main.go
Labels: size/XXL, lgtm, approved
