Repository IBM/ibm-cert-manager-operator, pull requests merged in 2023-01, with the labels that each got.

#302 remove finalizer
  controllers/operator/certmanager_controller.go
Labels: lgtm, approved, size/M

#306 bump version for 3.19.8
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#308 update cert manager image versions
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#307 update cert manager image versions
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#305 remove finalizer in ltsr
  controllers/operator/certmanager_controller.go
Labels: lgtm, approved, size/S

#311 new artifactory image endpoint (cert manager)
  Dockerfile
  Dockerfile.orig
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: lgtm, approved, size/S

#312 [ltsr] new artifactory image endpoint (cert manager)
  Dockerfile
  Dockerfile.orig
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: lgtm, approved, size/S

#313 [future] new artifactory image endpoint (cert manager)
  Dockerfile
  Dockerfile.orig
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: lgtm, approved, size/S

#310 [CP3.0] Standalone cert-manager
  Makefile
  apis/certmanager/v1alpha1/certificate_types.go
  apis/certmanager/v1alpha1/certificaterequest_types.go
  apis/certmanager/v1alpha1/challenge_types.go
  apis/certmanager/v1alpha1/const.go
  apis/certmanager/v1alpha1/doc.go
  apis/certmanager/v1alpha1/groupversion_info.go
  apis/certmanager/v1alpha1/issuer_types.go
  apis/certmanager/v1alpha1/order_types.go
  apis/certmanager/v1alpha1/types.go
  apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/acme.cert-manager.io_challenges.yaml
  bundle/manifests/acme.cert-manager.io_orders.yaml
  bundle/manifests/cert-manager.io_certificaterequests.yaml
  bundle/manifests/cert-manager.io_certificates.yaml
  bundle/manifests/cert-manager.io_clusterissuers.yaml
  bundle/manifests/cert-manager.io_issuers.yaml
  bundle/manifests/certmanager.k8s.io_certificaterequests.yaml
  bundle/manifests/certmanager.k8s.io_certificates.yaml
  bundle/manifests/certmanager.k8s.io_challenges.yaml
  bundle/manifests/certmanager.k8s.io_orders.yaml
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/patch-metadata.sh
  config/crd/bases/acme.cert-manager.io_challenges.yaml
  config/crd/bases/acme.cert-manager.io_orders.yaml
  config/crd/bases/cert-manager.io_certificaterequests.yaml
  config/crd/bases/cert-manager.io_certificates.yaml
  config/crd/bases/cert-manager.io_clusterissuers.yaml
  config/crd/bases/cert-manager.io_issuers.yaml
  config/crd/bases/certmanager.k8s.io_certificaterequests.yaml
  config/crd/bases/certmanager.k8s.io_certificates.yaml
  config/crd/bases/certmanager.k8s.io_issuers.yaml
  config/crd/bases/certmanager.k8s.io_orders.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/cert-manager/certificaterefresh_controller.go
  controllers/cert-manager/podrefresh_controller.go
  controllers/cert-manager/suite_test.go
  controllers/cert-manager/v1_add_label_controller.go
  controllers/cert-manager/v1alpha1_add_label_controller.go
  controllers/certmanager/certificate_controller.go
  controllers/certmanager/certificate_converter.go
  controllers/certmanager/certificaterequest_controller.go
  controllers/certmanager/challenge_controller.go
  controllers/certmanager/issuer_controller.go
  controllers/certmanager/issuer_converter.go
  controllers/certmanager/order_controller.go
  controllers/certmanager/suite_test.go
  controllers/operator/certmanager_controller.go
  controllers/resources/constants.go
  controllers/resources/util.go
  main.go
Labels: size/XXL, lgtm, approved

#316 bump to v3.25.1 for v3.23.1
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#315 Add suggest namespace
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  controllers/resources/constants.go
  controllers/resources/util.go
Labels: lgtm, approved, size/S
