Repository IBM/ibm-cert-manager-operator, pull requests merged in 2023-04, with the labels that each got.

#332 ltsr migrate to aws
  common/Makefile.common.mk
Labels: lgtm, size/XS, approved

#331 cp3 migrate to aws
  common/Makefile.common.mk
Labels: lgtm, size/XS, approved

#329 compare resource.Quantity type
  controllers/operator/deploys.go
Labels: lgtm, approved, size/S

#330 convert resource.quantity to string
  controllers/operator/deploys.go
  controllers/resources/certmanager.go
Labels: lgtm, approved, size/M

#334 license accept field and idling
  apis/operator/v1/certmanagerconfig_types.go
  apis/operator/v1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_certmanagerconfigs.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_certmanagerconfigs.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  controllers/operator/certmanager_controller.go
  controllers/resources/certmanager.go
Labels: lgtm, approved, size/L
