Repository IBM/ibm-cert-manager-operator, pull requests merged in 2023-08, with the labels that each got.

#361 [Cert Manager] bump version to 4.2.0
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/samples/operator_v1_certmanagerconfig.yaml
  controllers/resources/certmanager.go
Labels: lgtm, approved, size/S

#362 bump version to 3.25.7
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#363 [ltsr] keep restart labels backward compatible
  controllers/cert-manager/podrefresh_controller.go
Labels: lgtm, size/XS, approved

#365 remove unused code in cert manager
  controllers/operator/prereqs.go
  controllers/operator/util.go
  controllers/resources/constants.go
  controllers/resources/crd_variables.go
  controllers/resources/crds.go
  controllers/resources/smoke_check.go
  controllers/resources/v1crds/certificaterequests.yaml
  controllers/resources/v1crds/certificates.yaml
  controllers/resources/v1crds/challenges.yaml
  controllers/resources/v1crds/clusterissuers.yaml
  controllers/resources/v1crds/issuers.yaml
  controllers/resources/v1crds/orders.yaml
Labels: size/XXL, lgtm, approved
