Repository IBM/ibm-cert-manager-operator, pull requests merged in 2023-07, with the labels that each got.

#347 update packages for whitesource issue
  controllers/operator/deploys.go
  controllers/resources/containers.go
  go.mod
  go.sum
Labels: lgtm, approved, size/XL

#349 update jwt to 4.4.3
  go.mod
  go.sum
Labels: lgtm, size/XS, approved

#350 update packages for 4.1
  controllers/operator/deploys.go
  controllers/resources/containers.go
  go.mod
  go.sum
Labels: lgtm, approved, size/XL

#352 update go-restful to 3.10
  go.mod
  go.sum
Labels: lgtm, size/XS, approved

#351 update cr version
  controllers/operator/certmanager_controller.go
Labels: lgtm, approved, size/M

#353 bump version for 3.19.14
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#355 update license accept message
  controllers/operator/certmanager_controller.go
Labels: lgtm, size/XS, approved

#356 added dependabot file to scan for security fixes
  .github/dependabot.yml
Labels: lgtm, approved, size/S
