Repository IBM/ibm-cert-manager-operator, pull requests merged in 2023-02, with the labels that each got.

#317 Bump certmanager CR version
  apis/operator/v1/certmanager_types.go
  apis/operator/v1/groupversion_info.go
  apis/operator/v1/zz_generated.deepcopy.go
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_certmanagers.yaml
  common/config/.golangci.yml
  config/crd/bases/operator.ibm.com_certmanagers.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/samples/kustomization.yaml
  config/samples/operator_v1_certmanager.yaml
  controllers/operator/certmanager_controller.go
  controllers/operator/deploys.go
  controllers/operator/prereqs-webhook.go
  controllers/operator/prereqs.go
  controllers/operator/suite_test.go
  main.go
Labels: lgtm, approved, size/L

#319 update pkg for twistlock
  go.mod
  go.sum
Labels: lgtm, size/XS, approved

#322 Change the crd name to CertManagerConfig
  CONTRIBUTING.md
  PROJECT
  apis/operator/v1/certmanagerconfig_types.go
  apis/operator/v1/zz_generated.deepcopy.go
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_certmanagerconfigs.yaml
  config/crd/bases/operator.ibm.com_certmanagerconfigs.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/operator_v1_certmanagerconfig.yaml
  controllers/operator/certmanager_controller.go
  controllers/operator/deploys.go
  controllers/operator/prereqs-webhook.go
  controllers/operator/prereqs.go
Labels: lgtm, approved, size/L

#320 Create certmanager cr at runtime
  controllers/operator/certmanager_controller.go
  controllers/resources/certmanager.go
Labels: lgtm, approved, size/M
