Repository IBM/ibm-cert-manager-operator, pull requests merged in 2024-01, with the labels that each got.

#388 Update version and CRDs to sync with community version 1.13.3
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/crd/bases/acme.cert-manager.io_challenges.yaml
  config/crd/bases/acme.cert-manager.io_orders.yaml
  config/crd/bases/cert-manager.io_certificaterequests.yaml
  config/crd/bases/cert-manager.io_certificates.yaml
  config/crd/bases/cert-manager.io_clusterissuers.yaml
  config/crd/bases/cert-manager.io_issuers.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/samples/operator_v1_certmanagerconfig.yaml
  controllers/resources/certmanager.go
Labels: size/XXL, lgtm, approved

#389 make bundle to match the config and bundle CRDs
  bundle/manifests/acme.cert-manager.io_challenges.yaml
  bundle/manifests/cert-manager.io_certificaterequests.yaml
  bundle/manifests/cert-manager.io_certificates.yaml
  bundle/manifests/cert-manager.io_clusterissuers.yaml
  bundle/manifests/cert-manager.io_issuers.yaml
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#384 Webhook set readOnlyRootFileSystem to true
  controllers/operator/deploys.go
  controllers/resources/containers.go
Labels: lgtm, size/XS, approved

#390 Service labelling
  apis/operator/v1/certmanagerconfig_types.go
  apis/operator/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.ibm.com_certmanagerconfigs.yaml
  controllers/operator/certmanager_controller.go
  controllers/operator/deploys.go
  controllers/operator/util.go
  controllers/resources/constants.go
  controllers/resources/deployments.go
Labels: lgtm, approved, size/L

#391 move cert-manager version down to 4.2.2
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/samples/operator_v1_certmanagerconfig.yaml
  controllers/resources/certmanager.go
Labels: lgtm, approved, size/M

#392 [ltsr] webhook readOnlyRootFileSystem to true
  controllers/operator/deploys.go
  controllers/resources/containers.go
Labels: lgtm, size/XS, approved

#394 keep community version as 1.13.3
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M
