Repository IBM/ibm-cert-manager-operator, pull requests merged in 2024-10, with the labels that each got.

#440 bump cert-manager to 4.2.10 for SC2 4.6.8
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/samples/operator_v1_certmanagerconfig.yaml
  controllers/resources/certmanager.go
Labels: lgtm, approved, size/M

#439 remove ltsr branch from dependabot.yml
  .github/dependabot.yml
Labels: lgtm, size/XS, approved

#441 added instana configuration
  apis/operator/v1/certmanagerconfig_types.go
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_certmanagerconfigs.yaml
  config/crd/bases/operator.ibm.com_certmanagerconfigs.yaml
  controllers/operator/deploys.go
Labels: lgtm, approved, size/L
