Repository IBM/ibm-cert-manager-operator, pull requests merged in 2024-08, with the labels that each got.

#430 bump cert-manager to 4.2.8 for 4.6.6 release
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/samples/operator_v1_certmanagerconfig.yaml
  controllers/resources/certmanager.go
Labels: lgtm, approved, size/M

#429 add securityContext .seccompProfile field
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/resources/containers.go
  controllers/resources/pods.go
Labels: lgtm, approved, size/S

#431 updated base image to ubi9
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  go.mod
  go.sum
Labels: lgtm, approved, size/S

#432 trigger new build
  README.md
Labels: size/XS, approved

#433 updated ppc qemu image to v7.2.0-1
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: lgtm, size/XS, approved
