Repository IBM/ibm-cert-manager-operator, pull requests merged in 2025-05, with the labels that each got.

#465 Updated operatorNamespace value to certmgrNamespace
  helm-cluster-scoped/templates/cluster-rbac.yaml
  helm-cluster-scoped/values.yaml
  helm/templates/deployment.yaml
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: lgtm, approved, size/S

#467 bump cert-manager to 4.2.16 for cs 4.6.15
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/samples/operator_v1_certmanagerconfig.yaml
  controllers/resources/certmanager.go
  helm-cluster-scoped/Chart.yaml
  helm/Chart.yaml
  helm/templates/deployment.yaml
Labels: lgtm, approved, size/M

#463 Create no olm migration chart for IBM cert manager
  cert-manager-migration/Chart.yaml
  cert-manager-migration/templates/cert-manager-migration-job.yaml
  cert-manager-migration/templates/rbac.yaml
  cert-manager-migration/values.yaml
Labels: lgtm, approved, size/L
