Repository IBM/ibm-cert-manager-operator, pull requests merged in 2025-03, with the labels that each got.

#455 fix: set runAsNonRoot: true in controller deploy
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, size/XS, approved

#456 bump cert-manager to 4.2.14 for cs 4.6.12
  Makefile
  bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
  config/samples/operator_v1_certmanagerconfig.yaml
  controllers/resources/certmanager.go
Labels: lgtm, approved, size/M

#458 update net pkg to 0.36.0 for sc2 4.6.12
  go.mod
  go.sum
Labels: lgtm, approved, size/S
